{"name": "登录接口--正确的用户名、错误的密码", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert '99998' == '0'\n  - 0\n  + 99998", "trace": "@pytest.mark.xfail\n    @allure.feature(\"媒资库后台管理\")\n    @allure.story(\"管理后台User接口\")\n    @allure.title(\"登录接口--正确的用户名、错误的密码\")\n    @allure.description(\"传入正确的用户名、错误的密码\")\n    def test_login003():\n        username=data['login'][2]['Params']['username']\n        password=data['login'][2]['Params']['password']\n        # 对密码进行加密\n        password = get_str_sha1(password)\n        response=login(username=username,password=password)\n        # 断言\n>       assert response['response']['code'] == '0'\nE       AssertionError: assert '99998' == '0'\nE         - 0\nE         + 99998\n\nlogin\\test_login.py:51: AssertionError"}, "description": "传入正确的用户名、错误的密码", "attachments": [{"name": "log", "source": "f9173252-443f-4d32-b73b-b596442dc76c-attachment.txt", "type": "text/plain"}], "start": 1629099480387, "stop": 1629099480411, "uuid": "9d7de376-cbf2-4f29-bac9-5c9c19c04c0c", "historyId": "a5f60c30b1dcc9c25ebc341272322397", "testCaseId": "fd1051b11a9038c8c6386d820510d746", "fullName": "login.test_login#test_login003", "labels": [{"name": "feature", "value": "媒资库后台管理"}, {"name": "story", "value": "管理后台User接口"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "login"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-03G54LT"}, {"name": "thread", "value": "31592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login.test_login"}]}